services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  redis:
    image: redis
  app:
    build:
      dockerfile: Dockerfile.development
    depends_on:
      - db
      - redis
    environment:
      SECRET_KEY_BASE_DUMMY: 1
      PGHOST: db
      PGUSER: postgres
      PGPASSWORD: postgres
      REDIS_URL: redis://redis
      MEMCACHE_SERVERS: memcache