env:
  REGISTRY_SLUG: "buildkite-hosted-compose"

steps:
  - name: "Build app image"
    key: image_build
    plugins:
      - docker-compose#v5.6.0:
          build: app
          config: "docker-compose.ci.yml"
          retry:
            automatic:
              - limit: 2
                exit_status: 17
          propagate-environment: true
  - group: ':mag: QA'
    id: qa
    depends_on: image_build
    steps:
    - name: ":rubocop: run rubocop"
      command: bundle exec rubocop
      plugins:
        - docker-compose#v5.6.0:
            run: app
            config: "docker-compose.ci.yml"
            retry:
              automatic:
                - limit: 2
                  exit_status: 17
            propagate-environment: true
    - name: ":rspec: run tests"
      command: .buildkite/scripts/ci-runtests
      plugins:
        - docker-compose#v5.6.0:
            run: app
            config: "docker-compose.ci.yml"
            retry:
              automatic:
                - limit: 2
                  exit_status: 17
            propagate-environment: true
  - name: ":ship: production app image"
    plugins:
      - ./.buildkite/plugins/packages-docker-login:
            org_slug: "$BUILDKITE_ORGANIZATION_SLUG"
            registry_slug: "$REGISTRY_SLUG" # this is typically the name of your project
    command: .buildkite/scripts/ci-imagebuild
    key: prod_image_build
    depends_on: qa
